version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web_python
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db_python
    environment:
      - POSTGRES_USER=user_dev
      - POSTGRES_PASSWORD=pass_dev
      - POSTGRES_DB=server_dev

volumes:
  postgres_data: