version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn real_estate_server.wsgi:application --bind 0.0.0.0:8000"
    container_name: web_python
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db_python
    environment:
      - POSTGRES_USER=root_user
      - POSTGRES_PASSWORD=nq4242DNe343qrnd
      - POSTGRES_DB=domivka

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    container_name: nginx_python
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: