# Generated by Django 4.0.4 on 2022-05-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='real_estate/')),
                ('price', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('type_real_estate', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office')], default='house', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='real_estate_images/')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.realestate')),
            ],
        ),
    ]
