# Generated by Django 4.0.4 on 2022-05-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='real_estate/'),
        ),
    ]
