# Generated by Django 4.0.4 on 2022-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_realestate_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='service_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='rent', max_length=4),
        ),
    ]
