# Generated by Django 4.0.4 on 2022-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_realestate_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
    ]
