# Generated by Django 4.0.4 on 2022-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
    ]
