# Generated by Django 4.0.4 on 2022-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='city_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='realestate',
            name='region_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
