# Generated by Django 4.0.4 on 2022-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_realestate_city_code_realestate_region_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
    ]
