# Generated by Django 4.0.4 on 2022-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_realestate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='city',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='region',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
