# Generated by Django 4.0.4 on 2022-05-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_alter_realestate_city_alter_realestate_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='viewed_phone',
            field=models.IntegerField(default=0),
        ),
    ]
