# Generated by Django 4.0.4 on 2022-05-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_realestate_viewed_realestate_viewed_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='realestate',
            name='service_type',
            field=models.CharField(choices=[('sale', 'Продаж'), ('rent', 'Оренда')], default='rent', max_length=4),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type_real_estate',
            field=models.CharField(choices=[('house', 'Дім'), ('apartment', 'Квартира'), ('office', 'Офіс')], default='house', max_length=10),
        ),
    ]
