# Generated by Django 4.0.4 on 2022-05-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_alter_realestateimage_real_estate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Set delimiter example: keyword1, keyword2,...')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
        ),
    ]
