# Generated by Django 4.0.4 on 2022-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='name',
            field=models.CharField(default='Нерухомість', max_length=255),
        ),
    ]
