# Generated by Django 4.0.4 on 2022-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/user/img/avatar.webp', upload_to='avatars/'),
        ),
    ]
